// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsMLIqYwBPOHpG67IbeU1AFoeDvxcI2M',
    appId: '1:129891340265:web:cbcfa320b1dbca14af8578',
    messagingSenderId: '129891340265',
    projectId: 'flutter-notes-sampleapp',
    authDomain: 'flutter-notes-sampleapp.firebaseapp.com',
    storageBucket: 'flutter-notes-sampleapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqKhOJCZgAz-3RESWFyEjFjyoJoZ4XR0',
    appId: '1:129891340265:android:f6309265529e4519af8578',
    messagingSenderId: '129891340265',
    projectId: 'flutter-notes-sampleapp',
    storageBucket: 'flutter-notes-sampleapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JtJ3UjoVdUAgH7WH-WIFfGBXT2FBmjI',
    appId: '1:129891340265:ios:64990988c5de8b85af8578',
    messagingSenderId: '129891340265',
    projectId: 'flutter-notes-sampleapp',
    storageBucket: 'flutter-notes-sampleapp.appspot.com',
    iosClientId: '129891340265-d98j72kl9fkh10hlqcttb72frad2mcbe.apps.googleusercontent.com',
    iosBundleId: 'com.flutternotes.flutternotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6JtJ3UjoVdUAgH7WH-WIFfGBXT2FBmjI',
    appId: '1:129891340265:ios:64990988c5de8b85af8578',
    messagingSenderId: '129891340265',
    projectId: 'flutter-notes-sampleapp',
    storageBucket: 'flutter-notes-sampleapp.appspot.com',
    iosClientId: '129891340265-d98j72kl9fkh10hlqcttb72frad2mcbe.apps.googleusercontent.com',
    iosBundleId: 'com.flutternotes.flutternotes',
  );
}
